### ISSUE TITLE
Login modal does not hide when switching to password reset page.

### ISSUE THREAD

**Issue by callmesabs** [AggressivelyMeows/SponsusFeaturesAndBugs#1]
**Describe the bug**
Login modal does not hide when switching to password reset page.

**To Reproduce**
0. Do not be logged in
1. Go to any page
2. Click on Log In
3. Click on "Forgot Your Password?"
4. Login modal does not hide.

**Expected behavior**
Login modal should disappear when switching to password reset page.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox latest stable, Chrome latest stable

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Note5
 - OS: Android 7.0
 - Browser: Chrome

**Comment by AggressivelyMeows** [comment]
Pretty easy fix, will patch it asap!
