### ISSUE TITLE
Issues with cards

### ISSUE THREAD

**Issue by yellowgerbil** [AggressivelyMeows/SponsusFeaturesAndBugs#108]
**Describe the bug**
A fan has emailed me that he had trouble sponsoring my content, I am going to paste his email to me:
"Well, I took the plunge and signed up on Sponsus ($10 level).  It seems sort of beta, frankly.  My experience included:

Could not use PayPal.

Could not use my first choice of credit card -- got a message saying "more information required" but no way to provide whatever information was needed.

Finally got my second card accepted, but...

Got two messages, one right below the other on the same page.  First one said "check here to pay right away to get access immediately".  Second message said, "You have already paid enough to unlock yellowgerbil content."  So I didn't check the box, returned to your page, and... everything is still locked.

No biggie, I can wait until the end of the month.  But it wasn't exactly an encouraging intro to Sponsus.  Too bad Patreon booted you, I've never had that kind of trouble with them."

**To Reproduce**

**Expected behavior**
He doesn't seem to be the only one having issues as I have received many notifications from a person trying to sponsor me and it keeps saying failed on the payment page. Haven't spoken to him, but assuming it is the same issues the other reader has brought up. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AggressivelyMeows** [comment]
Sorry to hear about this issue, im looking into it as fast as possible!

**Comment by brunoais** [comment]
@yellowgerbil One thing Cerulean didn't tell is that PayPal forces websites to self-sensor, so it cannot work on Sponsus.

**Comment by yellowgerbil** [comment]
@brunoais 
Yeah I mentioned that to them. I was kicked off both Patreon and Ko-fi for adult content so am very glad Sponsus exists :D

**Comment by AggressivelyMeows** [comment]
This looks like a bug with the proration system, can i have the username of the person who was having the problems to this email: ceru@sponsus.org? Theres too many transactions per day for me to just blindly look through.

**Comment by AggressivelyMeows** [comment]
PayPal support is in the early works right now, I cant give a fixed timeline but its on its way.
