### ISSUE TITLE
Unable to sponsor creator - "Sponsor <creatorname>" button does nothing

### ISSUE THREAD

**Issue by SilverScroll** [AggressivelyMeows/SponsusFeaturesAndBugs#109]
**Describe the bug**
The "Sponsor <creatorname>" button on the join/custom interface of the creator I joined the website for fails to have an effect. It is clickable, and the text is briefly replaced by a spinning symbol when it is clicked, but the site doesn't change, the creator does not show up under my sponsorships, nor do I get any sort of message or e-mail. This is consistent across browsers and devices.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to creator user page
2. Click on "Custom sponsorship"
3. Set any sponsorship amount
4. Click "Sponsor
5. Wait for payment information loading screen
6. Optional: check the "I want to pay now..." checkbox - it makes no difference either way
7. Click the "Sponsor <creatorname>" button

**Expected behaviour**
Some sort of confirmation message, as well as my sponsorship to the creator being established. Alternatively, a failure message, indicating what went wrong.

**Screenshots**
The only visible and temporary effect of clicking the button:
![grafik](https://user-images.githubusercontent.com/74962942/100084717-62cda000-2e4b-11eb-9f45-c6bb5c50ba4d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - Browser: Firefox 78.5.0esr (32-bit), Google Chrome 87.0.4280.66 official (64-bit), Microsoft Edge 87.0.664.47 official (64-bit)

**Smartphone (please complete the following information):**
 - Device: OnePlus 8 Pro
 - OS: Android 11 (Oxygen OS 11.0.11.IN11BA)
 - Browser: Samsung Internet 13.0.1.64, Puffin Browser 8.4.1.42141 (10042141), Chrome 86.0.4240.185

**Additional context**
This problem has existed for at least a month by this point.

**Comment by AggressivelyMeows** [comment]
Odd, im going to look into this and add more error messages.

**Comment by AggressivelyMeows** [comment]
This has been fixed, sorry for taking so long on this issue.
