### ISSUE TITLE
Custom sponsorship process stuck on "Please wait, we are checking some details... "

### ISSUE THREAD

**Issue by SilverScroll** [AggressivelyMeows/SponsusFeaturesAndBugs#110]
**Describe the bug**
Same creator and account as the last issue I submitted; this time I don't even get as far as before the fix, though! Immediately after the Select a Tier screen, the Payment Information screen that used to pop up briefly now becomes permanent.

**To Reproduce**
1. Go to creator user page
2. Click on "Custom sponsorship"
3. Set any sponsorship amount
4. Click "Sponsor"
5. Wait for "Payment Information - Please wait, we are checking some details..." screen to appear

**Expected behavior**
The waiting period ends after some time, and the page proceeds to the screen where you can choose whether to pay immediately and to confirm the sponsorship. Alternatively, an error message.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/74962942/101232969-58b26980-36b5-11eb-890d-2c9e7a3aa08b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - Browser: Firefox 78.5.0esr (32-bit), Google Chrome 87.0.4280.88 official (64-bit), Microsoft Edge 87.0.664.55 official (64-bit)

**Smartphone (please complete the following information):**
 - Device: OnePlus 8 Pro
 - OS: Android 11 (Oxygen OS 11.0.11.IN11BA)
 - Browser: Samsung Internet 13.0.1.64, Puffin Browser 8.5.0.42207 (10042207), Chrome 86.0.4240.185

**Additional context**
This is a new bug first observed today.

**Comment by AggressivelyMeows** [comment]
Bug was due to me forgetting to add a small line, should be working now!
