### ISSUE TITLE
Error "This profile does not exist" when clicking on "Sponsor at this tier"

### ISSUE THREAD

**Issue by ansorgem01** [AggressivelyMeows/SponsusFeaturesAndBugs#111]
**Describe the bug**
When clicking on "Sponsor at this tier" a full page error message appears.

**To Reproduce**
1. Go to 'profile'
2. Click on 'Sponsor this tier'
3. See error

**Expected behavior**
It should ask to join and then go through with the payment info.

**Screenshots**
[If applicable, add screenshots to help explain your problem.](url)

**Desktop (please complete the following information):**
 - OS: [MacOS 11.0.1]
 - Browser [chrome, edgei]
 - Version [most up to date]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AggressivelyMeows** [comment]
Could you provide more information such as which profile is causing the issue?

**Comment by ansorgem01** [comment]
Yes sure: I'm still in the process on creating the profile. https://sponsus.org/u/joahtheo

**Comment by AggressivelyMeows** [comment]
Alright, I can reproduce the error on my end. Ill get to work on figuring out the issue, might take a bit however since im quite tired and im about to sleep.

**Comment by ansorgem01** [comment]
thanks for responding so quickly, I will put promoting this profile on hold. Thank you

**Comment by AggressivelyMeows** [comment]
Alrighty, bug has been fixed!

**Comment by ansorgem01** [comment]
thank you
