### ISSUE TITLE
When creating NSFW post by re-ticking the NSFW checkbox, it shows error in publishing the post.

### ISSUE THREAD

**Issue by Konayachi** [AggressivelyMeows/SponsusFeaturesAndBugs#114]
**Describe the bug**
Failed to publish a post after ticking and unticking the NSFW button.
See also: #113

**To Reproduce**
1. Create a post in a non-NSFW profile.
2. Fill in normally.
3. In the Meta section, tick the NSFW.
4. In the Meta section, untick the NSFW.
5. In the Meta section, tick the NSFW.
6. Publish the post.
7. Error: `{"success":false,"error":"Sorry, there were some problems with your post: is_nsfw: unknown field","error_hash":{"is_nsfw":"unknown field"}}`

**Expected behavior**
The post is published and it has the NSFW tag.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - Browser firefox
 - Version 81

**Additional context**
n/a

**Comment by AggressivelyMeows** [comment]
I think this is fixed, i might have mashed my keyboard at somepoint and changed the name of is_nsfw's spec field. whoopsies
