### ISSUE TITLE
Is the site down?

### ISSUE THREAD

**Issue by yellowgerbil** [AggressivelyMeows/SponsusFeaturesAndBugs#116]
**Describe the bug**
I have been trying to access my Sponsus page all day. All the link images seem to be broken and when I do manage to open my page it is empty and says I have no sponsors. 
This is happening both on my computer and on my phone.

**Comment by AggressivelyMeows** [comment]
Since the API hasnt fallen offline in a good 5 hours, im going to say the problem has been fixed.

**Comment by yellowgerbil** [comment]
> Since the API hasnt fallen offline in a good 5 hours, im going to say the problem has been fixed.

Yeah it was around 10-11 that it started working. I was freaking out because both times I've been kicked it was just wake up and my page is gone, first from Patreon then from Ko-fi. I quite like Sponsus and hope you guys don't ever start up with that zero tolerance to nudity nonsense.

**Comment by AggressivelyMeows** [comment]
The majority of the reasons that cause platforms to do those actions is the credit card companies pressuring them into removing the content. I will try my best to ensure that we dont end up in the same situation.

**Comment by yellowgerbil** [comment]
> The majority of the reasons that cause platforms to do those actions is the credit card companies pressuring them into removing the content. I will try my best to ensure that we dont end up in the same situation.

I appreciate you giving people a place where they can create their stuff. I'm finally starting to get a nice little chunk in sponsors each month and would hate to yet again have to start from scratch.
Keep doing what you're doing, there are a bunch of us thankful this Christmas to have found an alternative to those other platforms.
