### ISSUE TITLE
Formatting lost when posting

### ISSUE THREAD

**Issue by Sakura02** [AggressivelyMeows/SponsusFeaturesAndBugs#118]
[Formatting lost when posting](https://gyazo.com/a353fc4699a5d58d257ad2dc63bbc1a7)

This may have occurred because I was using the markdown editor? or maybe because I switched between the markdown editor and the new editor in the middle of the post, not sure :( but all my bold formatting reflected in the editor did not translate when posted.

**Comment by AggressivelyMeows** [comment]
Bug seems to be down to a disconnect between the Markdown editor and what is rendered. You need to make sure there is not a space before the end of the bold.

**Comment by AggressivelyMeows** [comment]
I would highly recommend using the new editor
