### ISSUE TITLE
Description must be string when adding description in shop?

### ISSUE THREAD

**Issue by Sakura02** [AggressivelyMeows/SponsusFeaturesAndBugs#119]
When adding a description and I try to submit. I get this and I'm not sure if this is a bug or I'm doing something wrong?

![image](https://user-images.githubusercontent.com/15233810/102173359-74113780-3e60-11eb-9c1b-c3c4c78aa91e.png)

also when adding a new product this title says "Name for your Store" instead of maybe "Name of the product" unless I am adding the name of my store. I am confused XD

![image](https://user-images.githubusercontent.com/15233810/102173437-999e4100-3e60-11eb-9e06-b172768751e9.png)

**Comment by AggressivelyMeows** [comment]
Oh whoopsies, i forgot to update the server with the new definitions
