### ISSUE TITLE
Access Tier Editing

### ISSUE THREAD

**Issue by dragon-architect** [AggressivelyMeows/SponsusFeaturesAndBugs#12]
Greetings, devs!

I didn't know whether to categorize this as a bug or a feature request, because it's a bit of both! At present it's not possible to change which tiers can access posts after they've been submitted. I would like for this setting to be editable post-publish!

I like to run my campaigns as an early access scheme, and I would like to be able to set the posts that have content accessible by the lowest pledge tier to be accessible to the public after the early-access period is up. I do already have an off-service gallery where I also publish this content for public access, so it's not a huge inconvenience to me, but I'm sure that for those who don't have such an alternate repository to make any early-access content publicly accessible, being able to make certain posts publicly accessible (or even to change which tiers can access them on a graduated basis) would be a handy feature!

Best regards,
Calyo

**Comment by AggressivelyMeows** [comment]
Hey, im really sorry that it took me so long to get back to you. For some reason, GitHub isnt telling me about updates anymore. I think that im going to allow the ability to change a posts price tbh, it kinda feels weird not being able to do so.

Thank you!
