### ISSUE TITLE
Storefront gives a warning if you don't upload a file

### ISSUE THREAD

**Issue by Sakura02** [AggressivelyMeows/SponsusFeaturesAndBugs#121]
The storefront gives an option to include a link or upload a file. However, even if you post a link, it gives a warning that it can't be published without files being uploaded? (You can bypass this and click publish anyway, but it's confusing)

![image](https://user-images.githubusercontent.com/15233810/102453093-297af100-4001-11eb-9f03-2781726041b0.png)

**Comment by AggressivelyMeows** [comment]
Added more information about why the box is there. Also added a checkbox to auto publish when a reward is added.
