### ISSUE TITLE
Account disappeared?

### ISSUE THREAD

**Issue by JenniferKohl** [AggressivelyMeows/SponsusFeaturesAndBugs#126]
I am unable to log in; when I click the login button nothing happens. My profile (jenniferkohl) shows no tiers, no posts, no backers, and no money, where yesterday I had lots of posts, 41 backers, and three tiers.

Issue suddenly started today. Appearing in both Firefox and Chrome on Win10.

**Comment by AggressivelyMeows** [comment]
Issue was due to the database being funky today. Ive reset it and it seems to be working again.

**Comment by JenniferKohl** [comment]
Thanks, it's working now!
