### ISSUE TITLE
Cannot publish progressive items without a file?

### ISSUE THREAD

**Issue by Sakura02** [AggressivelyMeows/SponsusFeaturesAndBugs#129]
Cannot publish progressive items without a file? (But there is no options for such) and I assume for progressive items there is no need for this requirement?

![image](https://user-images.githubusercontent.com/15233810/102922332-80465780-4453-11eb-8a5c-467611c91a7c.png)

**Comment by AggressivelyMeows** [comment]
Progressive products are not meant to be created yet, they were coming out later after i got the basics done.

**Comment by Sakura02** [comment]
> Progressive products are not meant to be created yet, they were coming out later after i got the basics done.

Ooo ok! Thanks looking forward to the final product.
