### ISSUE TITLE
Publishing a draft should update the date

### ISSUE THREAD

**Issue by JenniferKohl** [AggressivelyMeows/SponsusFeaturesAndBugs#13]
I just published a post that I'd been working on and saving as a draft for a couple of weeks, but it is still showing up on the date I _first_ saved it. That means even though it's my latest visible post, it's showing up _third_.

When a post that was previously saved as a draft is saved as not-a-draft, the date should update to reflect that.

Alternatively, any time the audience of a post changes--what tiers it's visible to, whether it's a draft, etc.--the date should be updated. However, I don't think the date should update for other changes (such as altering the text or title but keeping the audience the same).

**Comment by AggressivelyMeows** [comment]
Good idea! I'll look into changing this when I add the ability to schedule posts!
