### ISSUE TITLE
Clicking on 1 of the checkboxes of a Progressive product's checkbox field that has more than 1 checkbox, checks all checkboxes.

### ISSUE THREAD

**Issue by Konayachi** [AggressivelyMeows/SponsusFeaturesAndBugs#142]
**Describe the bug**
Clicking on 1 of the checkboxes of a Progressive product's checkbox field that has more than 1 checkbox, checks all checkboxes.   

**To Reproduce**
1. Go to https://sponsus.org/dashboard/store/product/1962618945953468416
2. Go under Progressive Fields
3. Click on New button
4. Select Checkbox type
5. Create 2 checkboxes
6. Click on Preview to test the checkboxes
7. Click on one of the checkboxes
8. Both checkboxes are checked

**Expected behavior**
Only the intended checkbox is checked.

**Desktop (please complete the following information):**
 - Browser: firefox
 - Version: 84

**Comment by AggressivelyMeows** [comment]
Keep in mind progressive products are not for public use, so its far more rough than the rest of the storefront.

**Comment by AggressivelyMeows** [comment]
Ok so, this is not a bug but an unintended side effect. You need to change the label of the checkbox for it to work because it generates a checkbox ID from the label so if it has the same label, it will treat them as the same checkbox.
