### ISSUE TITLE
Unable to Sponsor Creator

### ISSUE THREAD

**Issue by SamBrown512** [AggressivelyMeows/SponsusFeaturesAndBugs#152]
When I try to sponsor this creator I get this error message. I tried contacting them but they don’t know what’s going on. Another creator I started sponsoring the same day I tried this one went through just fine.

![101C1961-263A-4D8C-9F0A-D2A84ECAE34E](https://user-images.githubusercontent.com/81444450/112706309-d3c4a900-8e79-11eb-945f-f0b70d0033b9.jpeg)

**Comment by AggressivelyMeows** [comment]
Payouts not enabled on this creator means the creator you tried to sponsor has not finished the setup for their payout method. This is not a bug with Sponsus, you need to get in contact with the creator to get them to finish the signup process! ❤
