### ISSUE TITLE
Limit commenting based on sponsorship

### ISSUE THREAD

**Issue by PixievoltNo1** [AggressivelyMeows/SponsusFeaturesAndBugs#24]
**Is your feature request related to a problem? Please describe.**
I have a post that's a list of options for sponsorship benefits, and I'd like for people to be able to communicate to me which options they've chosen by commenting. Comments from people who don't qualify for those benefits are irrelevant.

**Describe the solution you'd like**
I'd like a "Price to comment on this post" option, much like the existing "Price to view this post".

**Describe alternatives you've considered**
I could use the "Price to view this post" option, but then people thinking about sponsoring me won't be able to see their options, giving them less motivation to sponsor me.

**Additional context**
[My profile](https://sponsus.org/u/pixievoltno1)

**Comment by AggressivelyMeows** [comment]
Intresting idea, ill add it to my todo list for sure!

**Comment by AggressivelyMeows** [comment]
If i may offer a solution for the mean time. If you create a public post and then ask people DM you, that would allow you to keep up to date with new entries.
