### ISSUE TITLE
I can't search up sponsors by name 

### ISSUE THREAD

**Issue by Pumpkin-Online** [AggressivelyMeows/SponsusFeaturesAndBugs#25]
I also cannot search up names, both when I partially type it out AND if I copy-paste the full name.**

Not critical, but a bit annoying because all of my sponsors are in one long list without any way to filter them or quickly verify a pledge by searching up a sponsor.

**Comment by Pumpkin-Online** [comment]
JK it's either working now or I just wasn't using it properly.

**Comment by AggressivelyMeows** [comment]
This has been something that people have been getting confused about so im going to add a notice that you need to click "search".
