### ISSUE TITLE
The amount a creator earns on their front page should be the final amount after fees, not the gross.

### ISSUE THREAD

**Issue by Pumpkin-Online** [AggressivelyMeows/SponsusFeaturesAndBugs#27]
For peace of mind and psychological reasons. A creator, as well as their supporters, do not need to know the gross amount, they mostly want to know what the final amount the creator will be getting after fees.

So I suggest only having the fee break down on the back-end in the creator's dashboard, and have the front page amount reflect and 'real' amount being earned. 

Patreon switched to doing this and it was met with positive feedback.

**Comment by ghost** [comment]
This should definitely be implemented before any planned fee increaase

**Comment by ghost** [comment]
Looks like this was implemented! You can close this now
