### ISSUE TITLE
Sponsor at a custom price

### ISSUE THREAD

**Issue by Admiralmatt** [AggressivelyMeows/SponsusFeaturesAndBugs#3]
I would like to allow users to sponsor me per month for any amount they want.

If a person wants to support me for $1 then i would need to create a $1 tier.
This means to allow people to support me i would need to create an indivudal tier for every single dollar amount.

**Comment by PixievoltNo1** [comment]
itch.io encourages buyers to pay an amount above the price set by the seller, and a lot of people do use that option ([source](https://itch.io/blog/2/running-an-indie-game-store-2015)).
