### ISSUE TITLE
Ability to customize "sponsor" term on creator page

### ISSUE THREAD

**Issue by ghost** [AggressivelyMeows/SponsusFeaturesAndBugs#32]
![image](https://user-images.githubusercontent.com/61886526/76124955-c5cf8c00-5fc9-11ea-8202-f0e65dd312f2.png)
![image](https://user-images.githubusercontent.com/61886526/76121948-e7794500-5fc2-11ea-9940-59c0c62d73dd.png)

Sponsus, by default, calls any users that become paying supporters of a creator "sponsors." Backing a creator is called "sponsoring." The site's culture (and branding) revolves around the word "sponsor" and understandably so, **BUT** this term can be misinterpreted by someone who hasn't heard of Sponsus. 

This issue especially applies to YouTube creators, as "sponsorships" on YouTube means placing paid advertisements in the middle of a video. A YouTube creator referring to their valuable Sponsus supporters as "sponsors" can rub their audience the wrong way, as sites like Sponsus and Patreon usually exist as an alternative to a creator taking on corporate sponsorship deals.

To avoid this confusion, Sponsus should take a page out of Ko-fi's book and allow creators to customize this term for their own creator pages. Replacing "Sponsor at this tier" with "Pledge/Support/Back at this tier" can not only clear up all of this confusion, but can be also used as a great way to add more personality to a page, like "Enlist now" or "Join the crew." Creators can refer to their paying audience in more creative ways, adding another element of appeal to using Sponsus.

![image](https://user-images.githubusercontent.com/61886526/76124927-bcdeba80-5fc9-11ea-9da3-d0f108c411c9.png)
![image](https://user-images.githubusercontent.com/61886526/76124687-43df6300-5fc9-11ea-88c2-6018adf627f8.png)
![image](https://user-images.githubusercontent.com/61886526/76124706-4f328e80-5fc9-11ea-9086-e8ebe88f826e.png)
![image](https://user-images.githubusercontent.com/61886526/76124718-578ac980-5fc9-11ea-94ce-0bd71444400b.png)
![image](https://user-images.githubusercontent.com/61886526/76124793-7ab57900-5fc9-11ea-82b4-f98fd997aa0a.png)

Do note that this setting shouldn't have to expand all the way into renaming the "Sponsorships" panel in settings. These changes should only be a layer of customization on a creator page.

It's hard to emulate something like what Patreon did because of how long they've been around: it's customary to refer to monthly support programs on YouTube simply as "a Patreon" and any backers as "patrons." Sponsus may harm its appeal if it tries to contend with the term "sponsor" on the site, so a creator should be able to customize the Call to Action of sponsoring.

**Comment by AggressivelyMeows** [comment]
Im going to remove this from the public todo as it is a far down the line feature request. I'll add it to my notes however!
