### ISSUE TITLE
Dark theme search bugs

### ISSUE THREAD

**Issue by ghost** [AggressivelyMeows/SponsusFeaturesAndBugs#34]
There are problems with Sponsus' dark theme styling when it comes to searching.

1. Go to any Sponsus creator's page
2. Click on the text box of the search bar
3. Keeping the cursor in the box active, move your mouse away from the box- **the background will turn white**
4. Type any random string into the box and hit search- **the cat icon at the top is barely visible**

![image](https://user-images.githubusercontent.com/61886526/76126909-5c05b100-5fce-11ea-90d1-df60c418882f.png)
![image](https://user-images.githubusercontent.com/61886526/76126953-76d82580-5fce-11ea-9fe2-e15f237d8a37.png)

 - OS: Windows 10
 - Browser: Firefox
 - Version: 73.0.1

**Comment by n-aspen** [comment]
I actually have a video of this as well. 
![MOV-2020-03-18__6371](https://user-images.githubusercontent.com/16448318/77011715-de815f80-6942-11ea-9223-d9269c524925.gif)
