### ISSUE TITLE
An easy way to see a proper list of creators using the site

### ISSUE THREAD

**Issue by Pumpkin-Online** [AggressivelyMeows/SponsusFeaturesAndBugs#36]
The front page makes it looks like no one is using Sponsus. Even though there aren't many people on the site, you should have a way to just browse all the creators, not just find them via the search bar.

So either list everyone in a long list, and have tabs to break them up by some kind of category.

_.I personally almost didn't join Sponsus because I didn't think there was anyone was using it and it looked suspicious_. The search bar for creators was useless because I didn't know what key words to type to find literally anyone.

**Comment by AggressivelyMeows** [comment]
Discovery is coming soon to all users. This is a way to discover new creators while keeping it relevent to your topics of intrest.
