### ISSUE TITLE
Features Patreon has that Sponsus lacks.

### ISSUE THREAD

**Issue by Pumpkin-Online** [AggressivelyMeows/SponsusFeaturesAndBugs#39]
If you want to catch up/compete with Patreon here are some features Sponsus is lacking that I've noticed. These aren't critical features, but just pointing it out in case you want to consider implementing. 

**[Mass messaging sponsors, by tier](https://i.gyazo.com/c8cfb006e34e0bf5ae713085c986028a.png)**

[Ability to see how many sponsors are on a tier ](https://i.gyazo.com/bb10a53a48089763618b330f6a8a3b17.png)

**[Mass message a welcome to new sponsors](https://i.gyazo.com/51143c31810d8c2d5dce3cfadfb911f2.png)**

[Ability to see sponsor history in more detail in one place](https://i.gyazo.com/20f91faa1d9d5dc9e00b6602492e2c51.png)

**[Ability to pause or put a page on hiatus so no payments are being made](https://i.gyazo.com/fdf45dc91a3cb638cc9d188b80ee278e.png)**

**See how many people are supporting a creator**

**[Exit Surveys for the creators](https://images.ctfassets.net/tfws0ki30xlo/4tDCedmDr28kqGy424mQEu/964d21e8298827ac30e57c0b76229e13/exit_survey_720.jpg?fit=scale&q=100&w=1000)**

**[Unique thank you message based on tier pledge](https://i.gyazo.com/ddb6db5050f55059d56f5f68842e1257.png)**

**[Ability to see growth over month in the analaytics page.](https://i.gyazo.com/2d7166236e4942dd6efee2c1315578e3.png)**

**[Break down of growth again example.](https://i.gyazo.com/af8d827402a438f3a97cf4e04fcfbe9a.png)**

**Comment by ghost** [comment]
Looks like some of the list has been knocked out! These are remaining:

- Mass-messaging sponsors, whether they're new or by tier
- Ability to see sponsor history in more detail in one place
- Unique thank you messages for specific tiers

Other feature requests are already separately listed as #26, #29, and #56. (Preferably all the feature requests could be separated but it's not needed)

**Comment by AggressivelyMeows** [comment]
The first two on the updated list are now in Sponsus. Thank you notes have been added to the prio list.
