### ISSUE TITLE
Tier Changes not shown in editor

### ISSUE THREAD

**Issue by Admiralmatt** [AggressivelyMeows/SponsusFeaturesAndBugs#4]
i had a $1 tier created, i added discord rewards to that tier and hit save. it gave me the saved message.

in the screenshot below under manage my tiers it does not show that the tier has discord rewards. when i hit edit the part on top does say that. i am unable to be certain if the $1 tier does include a discord reward or not.

![Capture](https://user-images.githubusercontent.com/9373482/59800218-02305000-92b4-11e9-9f42-49eeddf81577.PNG)

i then checked my profile but the tier there also does not say that it has a discord reward. screenshot below

![Capture](https://user-images.githubusercontent.com/9373482/59800310-44599180-92b4-11e9-91e5-d92a4378cffc.PNG)

**Comment by AggressivelyMeows** [comment]
This is a known issue, im trying to figure out why its not showing. Ill update you when i work it out! Thanks for using Sponsus
