### ISSUE TITLE
I created a post that is locked by month, but it won't show.

### ISSUE THREAD

**Issue by Pumpkin-Online** [AggressivelyMeows/SponsusFeaturesAndBugs#40]
[Video of bug](https://i.gyazo.com/e05e1cfa68ddf6259c7a5980134b0f3e.mp4)

My post won't appear.

**Comment by AggressivelyMeows** [comment]
Issue seems to be related to the linkifyer, doesnt like animated emojis from what I can tell. I've fixed this bug and im going to close this issue.
