### ISSUE TITLE
Users confusing gifting with subscribing (possibly trying to change tier, but no option available)

### ISSUE THREAD

**Issue by Pumpkin-Online** [AggressivelyMeows/SponsusFeaturesAndBugs#50]
I'm reporting this as a bug because multiple users have had this problem, and they message me asking why they can't access my content. My guess is maybe they wanted to change their pledge, but there is no obvious way to do that from the creator page as all the buttons are replaced with gifting.

![image](https://user-images.githubusercontent.com/26829433/78860507-00c54500-79f8-11ea-9d87-9a14e4d1d94e.png)

_( Unrelated Side comment: I made report about this someplace, but need to have an obvious way to message creators form their front page. Most of my Sponsus supporters are contacting me with Sponsus related issues through other websites, and it makes it difficult to assist them because most times the names don't match up with their Sponsus name. But that's a separate issue)_

![image](https://user-images.githubusercontent.com/26829433/78860944-19822a80-79f9-11ea-9177-03a670af6e91.png)

**Confusing language after clicking gift**
I know there is a bright orange button that says gift code, but there is no other description explaining they are gifting a tier. Maybe change the wording, or explain what gifting is.

I also noticed something else. **If someone wants to change their pledge is there an easy way to do that?** I'm going to assume the person saw gift code under all the tiers and assumed that was the only way to maybe upgrade or change their tiers. And the wording I underlined above made it seem like they themselves were pledging.

**Recommendation for the Tier UI to avoid confusion**
 I would recommend having buttons **so if users want to change tiers they can easily do so from the front page without having to hunt for it in their dashboard or elsewhere.** It would also be handy to mark which tier the person is currently pledging on. If necessary, if you don't want to make things cluttered,  hierarchy wise the gifting option would need to be smaller as that would be used less often than if supporters want to upgrade or downgrade their tiers. 

**How Patreon does it.**

It says what the current person is pledging 

![image](https://user-images.githubusercontent.com/26829433/78899939-bebdf280-7a3b-11ea-99df-e779bb789d13.png)

More importantly, even though I already currently pledging, I can still see the option to switch pledges at any time.

![image](https://user-images.githubusercontent.com/26829433/78902973-2413e280-7a40-11ea-882a-d12e5deace42.png)

How Patreon does changing pledges. 

- The new changes don't kick in until the next month, if the pledge is lower. 

- If they change to a higher pledge, then it charges the difference from the current pledge and the person can access the higher tier rewards immediately.

**Comment by AggressivelyMeows** [comment]
Updated the checkout page as well as changed the button text. To gift, you need to click the text below the button.
