### ISSUE TITLE
Survey conducted on why my supporters are staying on patreon

### ISSUE THREAD

**Issue by Pumpkin-Online** [AggressivelyMeows/SponsusFeaturesAndBugs#51]
**DISCLAIMER!** The point of this is not to be discouraging, or be like well Sponsus can't do anything X Y and Z. The purpose of this is simply to share some data that may be useful for the direction and growth of Sponsus. It's easy to make assumptions about what people want in a service, and it's always nice to get proper feedback when available. So take a look at it, chew on it, take some time to digest, and figure out how to use this info to your advantage (if it's useful.) 

**Number of Supporters on Sponsus versus Patreon**

I have moved to Sponsus for 2 months now and I have 103 supporters still on Patreon and 88 supporters on Sponsus. So I conducted a poll to figure out why more people are still on Patreon.

My Patreon page is half-open. However, I don't make any blog posts, no polls, and everyone needs to wait until the end of the month for me to private message them their rewards. It's horribly inconvenient and despite explaining this, there are still more people on Patreon than rather moving to Sponsus. 

**Earnings on Sponsus Versus Patreon**

I am currently earning more on Sponsus than I am on Patreon. After fees I earn $1061 on patreon, and $1397 on Sponsus (as of writing this up). This means my bigger spenders are supporting Sponsus (possibly to redeem a custom commission that is only available on Sponsus due to the feature of having blog posts unlock based on time pledged. This reward can only be unlocked via pledging on one of my higher tiers of $20 for multiple months. So this means by taking advantage of one of Sponsus's unique features I've been able to get more out of 88 supporters than 103

**Poll on why my supporters are staying on Patreon** (39 responses) (users were able to select multiple choices if applicable)

![image](https://user-images.githubusercontent.com/26829433/78956360-a8e61700-7aa7-11ea-812e-ca666a0e04d6.png)

**Comments on this poll from my supporters**

![image](https://user-images.githubusercontent.com/26829433/78956438-e34fb400-7aa7-11ea-8d68-140c5df1dcb6.png)

An interesting observation from this feedback is. Despite me using none of Patreon's features, as long as I deliver on the rewards every month, even if it's slow. Supporters would rather stay for the reasons they have listed above.

**Earnings Data since the move**

 I no longer have access to Patreon's analytics, but before I moved my earnings would average $3000 - $3300. Adding up both Sponsus and Patreon current earnings I am currently at $2458 total. Which means I have lost at least $500 minimum because of the move. Possibly due to people who didn't/can't move to Sponsus, but also don't have the patience to stay on Patreon. Ouch. I mention this to illustrate, at least in my case, that moving from Patreon to Sponsus could possibly hurt a creator's income if they already have an established Patreon community. In my case, I can take the losses, but other creators probably can't take any kind of hit in their income and this may be a factor stopping people from switching over (if they have a choice). 

**Summary**

I'm only one case study so take this info with a grain of a salt. Hopefully, this will be useful

**Comment by ghost** [comment]
Incredibly insightful, thank you!
