### ISSUE TITLE
When editing posts it defaults to (don't lock tier)

### ISSUE THREAD

**Issue by Pumpkin-Online** [AggressivelyMeows/SponsusFeaturesAndBugs#52]
If you edit a locked tier post it auto defaults to (don't lock) 

![image](https://user-images.githubusercontent.com/26829433/79092567-ed2b1e80-7d16-11ea-9095-89d203bb9494.png)

Making it risky to edit locked post in case the user forgets to reset this setting. It should remember to the previous setting for being locked or unlocked when updating.

**Comment by AggressivelyMeows** [comment]
Resolved, the API was not saving the changes to the lock object when saved. Sorry about that!
