### ISSUE TITLE
Donation Suggestion (Low Priority)

### ISSUE THREAD

**Issue by Pumpkin-Online** [AggressivelyMeows/SponsusFeaturesAndBugs#53]
I could just be dumb, but hear me out here. So after being on Sponsus for  2 months I had no idea what the point of the donation button was? I set up and was vaguely thinking ok, well it's for taking donations obviously, but why would someone donate instead of just subscribing and getting continuous content? It seemed redundant and pointless and then it finally hit me.

"OHhh ok it's if someone wants to make a **_one-time donation_** to access to rewards instead of subscribing monthly" Omg that is an amazing idea. That is not explained or advertised...anywhere and I don't think any of my fans have ever used it. Everyone, usually just subscribes because that's just what everyone expects. And some creators even refer to subscribing as donating, to begin with so it's a tad bit confusing. 

**Suggestion**

Instead of having a button that says "Donate" which competes with and feels redundant to subscribing. It should say something like "One Time Donation" or something that indicates
that this is a way to make a one-time donation instead of subscribing because that's the strength/point of the donate option. 

![image](https://user-images.githubusercontent.com/26829433/79094306-b35d1680-7d1c-11ea-8a7a-d5728c809afa.png)

**Second Suggestion**

So as someone who is putting myself in the shoes of a visitor wanting to donate, this explanation doesn't help explain... I feel like this is something that belongs on the creator dashboard because it's not directed to the person about to donate it's directed to the creator. I would suggest something like:

_"Donating is a great way to support [creator username] without having to subscribe monthly."_

Short, simple, sweet, and explains the point of donating as opposed to subscribing.  And creators can explain that tiered posts are unlocked by donating. 

**Extra Suggestion**

You can get fancy and help the creators out by explaining that donating does have benefits and someone isn't donating $5 to get nothing, as opposed to someone subscribing for $5 and getting access to tiered posts. (The lack of explanation for that could be why no one uses the donate button).

**Comment by AggressivelyMeows** [comment]
Resolved, changed button name to One time donation as well as updated the DonateBox explaination box
