### ISSUE TITLE
Visual bug when adding new tiers

### ISSUE THREAD

**Issue by henry232323** [AggressivelyMeows/SponsusFeaturesAndBugs#6]
**Describe the bug**
Each time a tier is added, any other tiers appear below as copies of the original tier and only the newest one is unique.

**To Reproduce**
1. Create a tier
2. Create a second tier
3. Create a third tier. The second should now match the first.
4. May be repeated, third will match second and first and so forth

**Expected behavior**
Previously made tiers should not be changed to appear to match the first.

**Screenshots**
https://cdn.discordapp.com/attachments/402004098196570122/593624119065444395/sponsuserror.JPG

**Desktop (please complete the following information):**
 - Win10
 - Brave

**Comment by AggressivelyMeows** [comment]
Whoa boy, that doesnt look right
