### ISSUE TITLE
Add gift code stacking or remove the ability to simultaneously redeem many for one creator

### ISSUE THREAD

**Issue by ghost** [AggressivelyMeows/SponsusFeaturesAndBugs#61]
![image](https://user-images.githubusercontent.com/61886526/80398956-6e8dbf80-8886-11ea-85f3-b49ea9dc3ab1.png)

I'd like to be able to generate gift codes for my sponsors that they can redeem all at once, so the total adds up to periods longer than the current 3 month maximum. Apparently, it IS currently possible to use more than one gift code on a single account for a single creator, but the gift sponsorship durations don't stack, **meaning that any extra codes redeemed are completely wasted**.

Please do one of the following:
- keep this ability to redeem multiple codes and add stacking gift durations (preferred)
- prevent multiple codes for one creator from being redeemed at once altogether (the gift code page shouldn't let a user redeem extra codes if they're just going to do nothing)

**Comment by AggressivelyMeows** [comment]
Stacking gift codes may become a feature in the future however it requires a lot of time investment. For now, im going to disable using a gift code when you are already on a gifted sponsorship.
