### ISSUE TITLE
Dashboard Overview NSFW creators checkbox does nothing

### ISSUE THREAD

**Issue by ghost** [AggressivelyMeows/SponsusFeaturesAndBugs#66]
**Describe the bug**
The "Allow NSFW creators?" checkbox on the Dashboard's Overview pivot in the "Discover new creators" column does nothing.

**To Reproduce**
1. Go to [https://sponsus.org/dashboard/overview](https://sponsus.org/dashboard/overview)
2. Click on the "Allow NSFW creators?" checkbox
3. Observe that nothing has changed and there is no way to apply the change
4. Refresh the page and observe that the box is unchecked

**Expected behavior**
Toggling the "Allow NSFW creators?" checkbox should, at minimum, either auto-save the option's state or enable it to be applied/saved. Ideally, doing so would also refresh the discovery queue.

**Desktop (please complete the following information):**
 - OS: Linux - Xubuntu 20.04
 - Browser: Firefox
 - Version: 76.0

**Comment by AggressivelyMeows** [comment]
If there are no NSFW creators in your discovery feed, then Sponsus hasnt matched you with one yet. I can confirm this is working on my end. Ill look into remember the last selected option for the checkbox!
