### ISSUE TITLE
Fix and clarify Discord server showcase/module

### ISSUE THREAD

**Issue by ghost** [AggressivelyMeows/SponsusFeaturesAndBugs#67]
![image](https://user-images.githubusercontent.com/61886526/81736552-c3276200-9464-11ea-8490-d747ba64fa38.png)

This setting (located in Dashboard -> Socials -> Discord) does not add anything to my profile or any tiers with Discord rewards.

![image](https://user-images.githubusercontent.com/61886526/81737150-a8a1b880-9465-11ea-82cb-c7c06508c57c.png)

Regardless of whether this setting is turned on or off, every tier with Discord rewards has this special section displaying a role reward.

![image](https://user-images.githubusercontent.com/61886526/81737508-32518600-9466-11ea-8d12-334a4881230e.png)

Clicking on it takes you to this broken screen, regardless of whether that setting is on or off. I have my Discord server connected to my account, and SponsusBot is an admin on that server, so I'm not sure why this invite link generator isn't working.

I have a feeling this feature in general was started but not completed. For creators that want to have sponsor-only Discord servers, finishing this feature would make it a lot easier to guide new sponsors on how to join the server WITHOUT resorting to using profile cards. (Profile cards are public so anyone can click them. Locking this join button to paying sponsors is a lot more efficient)

![image](https://user-images.githubusercontent.com/61886526/81738040-0387df80-9467-11ea-8186-2083aa9e6450.png)

Also, it would help if this button's description turned into a call to action once someone is sponsoring, so that sponsor can easily click and join.

So in essence:
- fix the invite generator screen for Discord rewards
- have that screen only appear for paying sponsors
- change the button text itself so paying sponsors can easily navigate to the server

**Comment by AggressivelyMeows** [comment]
I will be working on our Discord integration shortly. It is in a state of disrepair and needs to be patched up. Ill let you know how its going in our public Discord.

**Comment by ghost** [comment]
Fixed!
