### ISSUE TITLE
Give SponsusBot a ping command

### ISSUE THREAD

**Issue by ghost** [AggressivelyMeows/SponsusFeaturesAndBugs#68]
This one's pretty straightforward- it would be nice to check the latency (in milliseconds) on SponsusBot with something like `s.ping` instead of just using any other command to check if it's online.

**Comment by AggressivelyMeows** [comment]
You can use s.status to show the status of the Discord server and its rewards. This can also be used to show if the bot is running or if its having issues with your server.
