### ISSUE TITLE
Stupid Question

### ISSUE THREAD

**Issue by FunnyPunch** [AggressivelyMeows/SponsusFeaturesAndBugs#7]
**Is your feature request related to a problem? Please describe.**
Stripe is not yet available in Poland.

**Describe the solution you'd like**
Do you know when they will be? Perhaps you may ask them?

**Describe alternatives you've considered**
Or perhaps you can partner (non exclusively of course) with some other group and use both Stripe and some other Company. Or perhaps just make Tutorial how to use the Stripe Atlas (I assume the US account is not free of charge, so you'd need an upkeep) and very importantly how to avoid double taxation (I know that "forgetting your income" is an option, but I doubt anyone of us really wants it).

**Additional context**
![Stripe](https://user-images.githubusercontent.com/52724917/60932341-d6562800-a2bd-11e9-910f-37cf03c29744.png)

I apologize if this was answered somewhere or if this is not a place. I wish everyone here the best.
Funny Punch aka Jan Negrey

**Comment by AggressivelyMeows** [comment]
I can ask Stripe when Poland support will be added however i cannot guarantee it. As with the other thing, Atlas is Stripes company creation tool, it doesnt mean global access which is confusing. Ill keep you updated here on whats going on, thank you for considering to use Sponsus

**Comment by AggressivelyMeows** [comment]
**Stripe responded:**

As of the moment, while we'd love to be able to provide our services more broadly to businesses in Poland, I'm afraid that we're not quite there yet. We’re currently getting started with a very small number of companies to gather feedback and make adjustments to the product. We have also seen a large influx of demand recently, surpassing the number of users we're ready to support at this time. However, we do have people working full-time to make this happen. And with the current feedback that we are receiving for Poland I can say that it's near. We will be focusing on Standard accounts first, then soon we will work on Express/Custom Accounts. We don't have a specific date on when the preview will open but we are hoping it will be really soon!​

However, good news is, if you'd like to be notified as soon as we are available more broadly. We might be able to send you invite to become one of the pioneer accounts once we go on beta and live in your country. For now, please sign up for our waiting list by registering your interest at:
