### ISSUE TITLE
CANNOT SAVE!

### ISSUE THREAD

**Issue by webzight** [AggressivelyMeows/SponsusFeaturesAndBugs#95]
CANNOT SAVE stuff using BOTH SAFARI and FIREFOX Developer !

Go save things in the PROFILE and THINGS don't STICK! 

Description, Avatar, and the OTHER TEXTS, NOT SAVING and/or SHOWING UP!

**Comment by AggressivelyMeows** [comment]
Hey there, since you seem to have FF Developers edit installed, would you be willing to send the console output for when you try to save? It seems to work for me on standard FF so any assistance with this would be great!
